---
resources:
# The repo with our Dockerfile
- name: go-sample-rest-source
  type: git
  icon: github
  source:
    uri: https://github.com/SergeyDz/go-sample-rest
    branch: master

# Where we will push the image
- name: go-sample-rest
  type: registry-image
  icon: docker
  source:
    # You need to provide these variables when
    # setting the pipeline
    repository: ((image-repo-name))/go-sample-rest
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-push
  plan:
  - get: go-sample-rest-source
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          repository: concourse/oci-build-task
      inputs:
      - name: go-sample-rest-source
      outputs:
      - name: image
      params:
        CONTEXT: go-sample-rest-source
        UNPACK_ROOTFS: "true" # only needed if using image in a future step
      run:
        path: build
  - put: go-sample-rest
    params:
      image: image/image.tar
      version: 2.0